"""test relationships

Revision ID: 1a02d6f54341
Revises: 47a6d21cc23d
Create Date: 2023-02-08 14:15:59.301512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a02d6f54341'
down_revision = '47a6d21cc23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('qr_code', table_name='job')
    op.drop_table('job')
    op.drop_table('ticket')
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fcm_token', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('device_hash', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('role_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ticket',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('job',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('final_price', mysql.FLOAT(), nullable=True),
    sa.Column('payment', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('deliver_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('qr_code', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('qr_code', 'job', ['qr_code'], unique=False)
    # ### end Alembic commands ###
