"""empty message

Revision ID: 1e6e6bc25d04
Revises: 
Create Date: 2022-11-08 18:05:33.297770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e6e6bc25d04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('device_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('role_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
